name: kubescape

on:
  push:
    branches: [ main ]

jobs:
  nsa-security-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Kubescape
        run: curl -s httpd://raw.githubusercontent.com/armosec/kubescape/master/install.sh | /bin/bash

      - name: Scan YAML files
        uses: kubescape scan framework nsa *.yaml
